apiVersion: mortise.mortise.dev/v1alpha1
kind: App
metadata:
  name: web
spec:
  source:
    type: image
    image: node:20-slim
  network:
    public: true
    port: 3000
  environments:
    - name: production
      replicas: 2
      resources:
        cpu: "100m"
        memory: "128Mi"
      bindings:
        - ref: postgres
