---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mortise.mortise.dev
  resources:
  - apps
  - gitproviders
  - platformconfigs
  - previewenvironments
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mortise.mortise.dev
  resources:
  - apps/finalizers
  - gitproviders/finalizers
  - platformconfigs/finalizers
  - previewenvironments/finalizers
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - mortise.mortise.dev
  resources:
  - apps/status
  - gitproviders/status
  - platformconfigs/status
  - previewenvironments/status
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
