apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortise
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mortise
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mortise
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mortise
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: mortise
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          args:
            - --api-bind-address=:{{ .Values.api.port }}
          env:
            - name: MORTISE_GITHUB_CLIENT_ID
              value: {{ .Values.github.clientID | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mortise
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mortise
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if and .Values.traefik.enabled (not .Values.ingress.className) }}
  ingressClassName: traefik
  {{- else if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mortise
                port:
                  number: {{ .Values.service.port }}
{{- end }}
