{{- if or .Values.registry.enabled .Values.buildkit.enabled .Values.observer.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "mortise.depsNamespace" . }}
  labels:
    {{- include "mortise.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
{{- end }}
