{{- if .Values.platformConfig.enabled }}
apiVersion: mortise.mortise.dev/v1alpha1
kind: PlatformConfig
metadata:
  name: platform
  labels:
    {{- include "mortise.labels" . | nindent 4 }}
spec:
  domain: {{ .Values.platformConfig.domain | default "" | quote }}
  {{- if .Values.platformConfig.externalDomain }}
  externalDomain: {{ .Values.platformConfig.externalDomain | quote }}
  {{- end }}
  {{- if or .Values.platformConfig.registry.url .Values.registry.enabled }}
  registry:
    {{- if .Values.platformConfig.registry.url }}
    url: {{ .Values.platformConfig.registry.url | quote }}
    {{- else }}
    url: http://{{ include "mortise.registryAddr" . }}
    pullURL: http://{{ include "mortise.registryPullAddr" . }}
    insecureSkipTLSVerify: true
    {{- end }}
    namespace: {{ .Values.platformConfig.registry.namespace | default "mortise" }}
    {{- if .Values.platformConfig.registry.insecureSkipTLSVerify }}
    insecureSkipTLSVerify: true
    {{- end }}
    {{- if .Values.platformConfig.registry.pullSecretRef }}
    pullSecretName: {{ .Values.platformConfig.registry.pullSecretRef | quote }}
    {{- end }}
  {{- end }}
  {{- if or .Values.platformConfig.build.buildkitAddr .Values.buildkit.enabled }}
  build:
    {{- if .Values.platformConfig.build.buildkitAddr }}
    buildkitAddr: {{ .Values.platformConfig.build.buildkitAddr | quote }}
    {{- else }}
    buildkitAddr: {{ include "mortise.buildkitAddr" . }}
    {{- end }}
    {{- if .Values.platformConfig.buildPlatform }}
    defaultPlatform: {{ .Values.platformConfig.buildPlatform }}
    {{- end }}
  {{- end }}
  {{- if .Values.platformConfig.tls.clusterIssuer }}
  tls:
    certManagerClusterIssuer: {{ .Values.platformConfig.tls.clusterIssuer | quote }}
  {{- end }}
  {{- if .Values.observer.enabled }}
  observability:
    logsAdapterEndpoint: http://mortise-observer.{{ include "mortise.depsNamespace" . }}.svc:9091
    metricsAdapterEndpoint: http://mortise-observer.{{ include "mortise.depsNamespace" . }}.svc:9091
    trafficAdapterEndpoint: http://mortise-observer.{{ include "mortise.depsNamespace" . }}.svc:9091
  {{- end }}
  defaults:
    resources:
      cpu: {{ (.Values.platformConfig.defaults).resources.cpu | default "100m" | quote }}
      memory: {{ (.Values.platformConfig.defaults).resources.memory | default "256Mi" | quote }}
{{- end }}
