{{- if .Values.platformConfig.enabled }}
apiVersion: mortise.mortise.dev/v1alpha1
kind: PlatformConfig
metadata:
  name: platform
  labels:
    {{- include "mortise.labels" . | nindent 4 }}
spec:
  domain: {{ .Values.platformConfig.domain | default "" | quote }}
  {{- if .Values.registry.enabled }}
  registry:
    url: http://{{ include "mortise.registryAddr" . }}
    pullURL: http://{{ include "mortise.registryPullAddr" . }}
    namespace: mortise
    insecureSkipTLSVerify: true
  {{- end }}
  {{- if .Values.buildkit.enabled }}
  build:
    buildkitAddr: {{ include "mortise.buildkitAddr" . }}
    {{- if .Values.platformConfig.buildPlatform }}
    defaultPlatform: {{ .Values.platformConfig.buildPlatform }}
    {{- end }}
  {{- end }}
  {{- if .Values.observer.enabled }}
  observability:
    logsAdapterEndpoint: http://mortise-observer.{{ include "mortise.depsNamespace" . }}.svc:9091
    metricsAdapterEndpoint: http://mortise-observer.{{ include "mortise.depsNamespace" . }}.svc:9091
    trafficAdapterEndpoint: http://mortise-observer.{{ include "mortise.depsNamespace" . }}.svc:9091
  {{- end }}
{{- end }}
