apiVersion: v1
kind: Service
metadata:
  name: mortise
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mortise
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/name: mortise
