{{- $metrics := .Values.metrics | default dict }}
apiVersion: v1
kind: Service
metadata:
  name: mortise
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mortise
  {{- if dig "enabled" true $metrics }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ dig "port" 8080 $metrics | quote }}
    prometheus.io/path: /metrics
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    {{- if dig "enabled" true $metrics }}
    - port: {{ dig "port" 8080 $metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: mortise
