apiVersion: v2
name: mortise
description: Self-hosted Railway-style deploy platform for Kubernetes (batteries included)
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: mortise-core
    version: "0.1.0"
    repository: "file://../mortise-core"

  - name: traefik
    version: "34.3.0"
    repository: "https://traefik.github.io/charts"
    condition: traefik.enabled

  - name: cert-manager
    version: "v1.17.1"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled

  - name: metrics-server
    version: "3.12.2"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
    condition: metricsServer.enabled
